### ISSUE TITLE
base_mt_schema.py, line 61 purpose

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/hail-elasticsearch-pipelines#180]
Hi,

I am not completely sure since I am relatively new to python, but I am just wondering, in the file 

https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/luigi_pipeline/lib/model/base_mt_schema.py

on line 61 there is such a thing:

```getattr(self, fn_require.__name__)()```

And you do not save the returned value anywhere it seems, so is it a bug, or how you get the returned value saved then?

For instance, if you pass 'fn_require=genotypes' like you do on line 204 in this file:

https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/luigi_pipeline/lib/model/seqr_mt_schema.py

Then ```getattr(self, fn_require.__name__)()``` just returns:

```hl.agg.collect(hl.struct(**self._genotype_fields()))```

Which is an array.

**Comment by nawatts** [comment]
Hi @NLSVTN,

It's assumed that the method specified by `fn_require` annotates the underlying MatrixTable when it is called. So the return value doesn't need to be stored because it's available on the MatrixTable. `fn_requires` is used to ensure that other annotations that the `row_annotation` method depends on are added first.

An example of this can be seen in SeqrSchema. `domains` is a `row_annotation` method with `fn_require=sorted_transcript_consequences`. `sorted_transcript_consequences` is also a `row_annotation` method and it creates the `sortedTranscriptConsequences` field on `self.mt` which the `domains` method uses. `fn_require` ensures that `sorted_transcript_consequences` is run before `domains`.
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/d6e9dedbce929c04c294c54095663ba94a4de3f0/luigi_pipeline/lib/model/seqr_mt_schema.py#L87-L90

https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/d6e9dedbce929c04c294c54095663ba94a4de3f0/luigi_pipeline/lib/model/seqr_mt_schema.py#L39-L41

**Comment by NLSVTN** [comment]
Thank you for explaining! Now I see, the thing that I missed was that 'genotypes' method is also annotated with '@row_annotation'.
